package ecar.pojo;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

// Generated 03/08/2006 10:18:55 by J-Querena using Hibernate Tools 3.1.0.beta5



/**
 * ConfigRelatorioCfgrel generated by hbm2java
 */
public class ConfigRelatorioCfgrel  implements java.io.Serializable {


	private static final long serialVersionUID = 2449408265446923927L;

	 private int codCfgrel;
     private ModeloRelatorioMrel modeloRelatorioMrel;
     private String tituloCfgrel;
     private String notaRodapeCfgrel;

     // Constructors

    /** default constructor */
    public ConfigRelatorioCfgrel() {
    }

	/** 
	 * minimal constructor
	 * 
	 * @author N/C
	 * @since N/C 
         * @param codCfgrel
	 */
    public ConfigRelatorioCfgrel(int codCfgrel) {
        this.codCfgrel = codCfgrel;
    }
    /** 
     * full constructor.<br>
     * 
     * @author N/C
	 * @since N/C 
     * @param codCfgrel
     * @param modeloRelatorioMrel
     * @param tituloCfgrel
     * @param notaRodapeCfgrel
     */
    public ConfigRelatorioCfgrel(int codCfgrel, ModeloRelatorioMrel modeloRelatorioMrel, String tituloCfgrel, 
    		String notaRodapeCfgrel) {
       this.codCfgrel = codCfgrel;
       this.modeloRelatorioMrel = modeloRelatorioMrel;
       this.tituloCfgrel = tituloCfgrel;
       this.notaRodapeCfgrel = notaRodapeCfgrel;
    }
    
    /**
     * @author N/C
	 * @since N/C 
     * @return int
     */
    // Property accessors
    public int getCodCfgrel() {
        return this.codCfgrel;
    }
    
    /**
     * @param codCfgrel
     * @author N/C
	 * @since N/C 
     */
    public void setCodCfgrel(int codCfgrel) {
        this.codCfgrel = codCfgrel;
    }
    
    /**
     * @author N/C
	 * @since N/C 
     * @return ModeloRelatorioMrel
     */
    public ModeloRelatorioMrel getModeloRelatorioMrel() {
        return this.modeloRelatorioMrel;
    }
    
    /**
     * @param modeloRelatorioMrel
     * @author N/C
	 * @since N/C 
     */
    public void setModeloRelatorioMrel(ModeloRelatorioMrel modeloRelatorioMrel) {
        this.modeloRelatorioMrel = modeloRelatorioMrel;
    }
    
    /**
     * @author N/C
	 * @since N/C 
     * @return String
     */
    public String getTituloCfgrel() {
        return this.tituloCfgrel;
    }
    
    /**
     * @param tituloCfgrel
     * @author N/C
	 * @since N/C 
     */
    public void setTituloCfgrel(String tituloCfgrel) {
        this.tituloCfgrel = tituloCfgrel;
    }
    
   /**
    * @author N/C
	* @since N/C 
    * @return String
    */
    public String getNotaRodapeCfgrel() {
        return this.notaRodapeCfgrel;
    }
    
    /**
     * @author N/C
	 * @since N/C 
     * @param notaRodapeCfgrel
     */
    public void setNotaRodapeCfgrel(String notaRodapeCfgrel) {
        this.notaRodapeCfgrel = notaRodapeCfgrel;
    }
    
    /**
     * @author N/C
	 * @since N/C 
	 * @return String
     */
    @Override
    public String toString() {
        return new ToStringBuilder(this)
            .append("codCfgrel", getCodCfgrel())
            .toString();
    }

    /**
     * @param other
     * @author N/C
	 * @since N/C 
	 * @return boolean
     */
    @Override
    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof ConfigRelatorioCfgrel) ) return false;
        ConfigRelatorioCfgrel castOther = (ConfigRelatorioCfgrel) other;
        return new EqualsBuilder()
            .append(this.getCodCfgrel(), castOther.getCodCfgrel())
            .isEquals();
    }

    /**
     * @author N/C
	 * @since N/C 
	 * @return int
     */
    @Override
    public int hashCode() {
        return new HashCodeBuilder()
            .append(getCodCfgrel())
            .toHashCode();
    }

}


