package ecar.pojo;

// Generated 04/11/2008 17:38:44 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * TbHistoricoEttath generated by hbm2java
 */
public class HistoricoEttath implements java.io.Serializable {
	
	private static final long serialVersionUID = 7502382793713371641L;
	private Long codEttath;
	private UsuarioUsu usuarioUsuByCodUsuInclusao;
	private EstruturaEtt estruturaEtt;
	private AtributosAtb atributosAtb;
	private UsuarioUsu usuarioUsuByCodUsuUltManut;
	private HistoricoMaster historicoMaster;
//	
	private Character indObrigatorioEttat;
	private Character indListagemImpressCompEttat;
	private Integer seqApresListagemTelaEttat;
	private Integer larguraListagemTelaEttat;
	private Character indListagemTelaEttat;
	private Integer seqApresentTelaCampoEttat;
	private String labelEstruturaEttat;
	private Character indListagemImpressaResEttat;
	private Character indRelacaoImpressaEttat;
	private Character indRevisao;
	private String dicaEttat;
	private Character indListagemItensEttat;
	private Integer tamanhoConteudoAtribEttat;
	private Character indPodeBloquearEttat;
	private Character indFiltroEttat;
	private String documentacaoEttat;
	private Character indExcluidoEttat;
	private Date dataUltManutencaoEttat;
	private Date dataInclusaoEttat;

        /**
         *
         */
        public HistoricoEttath() {
	}

        /**
         *
         * @return
         */
        public Long getCodEttath() {
		return codEttath;
	}

        /**
         *
         * @param codEttath
         */
        public void setCodEttath(Long codEttath) {
		this.codEttath = codEttath;
	}

        /**
         *
         * @return
         */
        public UsuarioUsu getUsuarioUsuByCodUsuInclusao() {
		return usuarioUsuByCodUsuInclusao;
	}

        /**
         *
         * @param usuarioUsuByCodUsuInclusao
         */
        public void setUsuarioUsuByCodUsuInclusao(UsuarioUsu usuarioUsuByCodUsuInclusao) {
		this.usuarioUsuByCodUsuInclusao = usuarioUsuByCodUsuInclusao;
	}

        /**
         *
         * @return
         */
        public EstruturaEtt getEstruturaEtt() {
		return estruturaEtt;
	}

        /**
         *
         * @param estruturaEtt
         */
        public void setEstruturaEtt(EstruturaEtt estruturaEtt) {
		this.estruturaEtt = estruturaEtt;
	}

        /**
         *
         * @return
         */
        public AtributosAtb getAtributosAtb() {
		return atributosAtb;
	}

        /**
         *
         * @param atributosAtb
         */
        public void setAtributosAtb(AtributosAtb atributosAtb) {
		this.atributosAtb = atributosAtb;
	}

        /**
         *
         * @return
         */
        public UsuarioUsu getUsuarioUsuByCodUsuUltManut() {
		return usuarioUsuByCodUsuUltManut;
	}

        /**
         *
         * @param usuarioUsuByCodUsuUltManut
         */
        public void setUsuarioUsuByCodUsuUltManut(UsuarioUsu usuarioUsuByCodUsuUltManut) {
		this.usuarioUsuByCodUsuUltManut = usuarioUsuByCodUsuUltManut;
	}

        /**
         *
         * @return
         */
        public HistoricoMaster getHistoricoMaster() {
		return historicoMaster;
	}

        /**
         *
         * @param historicoMaster
         */
        public void setHistoricoMaster(HistoricoMaster historicoMaster) {
		this.historicoMaster = historicoMaster;
	}

        /**
         *
         * @return
         */
        public Character getIndObrigatorioEttath() {
		return indObrigatorioEttat;
	}

        /**
         *
         * @param indObrigatorioEttath
         */
        public void setIndObrigatorioEttath(Character indObrigatorioEttath) {
		this.indObrigatorioEttat = indObrigatorioEttath;
	}

        /**
         *
         * @return
         */
        public Character getIndObrigatorioEttat() {
		return indObrigatorioEttat;
	}

        /**
         *
         * @param indObrigatorioEttat
         */
        public void setIndObrigatorioEttat(Character indObrigatorioEttat) {
		this.indObrigatorioEttat = indObrigatorioEttat;
	}

        /**
         *
         * @return
         */
        public Character getIndListagemImpressCompEttat() {
		return indListagemImpressCompEttat;
	}

        /**
         *
         * @param indListagemImpressCompEttat
         */
        public void setIndListagemImpressCompEttat(Character indListagemImpressCompEttat) {
		this.indListagemImpressCompEttat = indListagemImpressCompEttat;
	}

        /**
         *
         * @return
         */
        public Integer getSeqApresListagemTelaEttat() {
		return seqApresListagemTelaEttat;
	}

        /**
         *
         * @param seqApresListagemTelaEttat
         */
        public void setSeqApresListagemTelaEttat(Integer seqApresListagemTelaEttat) {
		this.seqApresListagemTelaEttat = seqApresListagemTelaEttat;
	}

        /**
         *
         * @return
         */
        public Integer getLarguraListagemTelaEttat() {
		return larguraListagemTelaEttat;
	}

        /**
         *
         * @param larguraListagemTelaEttat
         */
        public void setLarguraListagemTelaEttat(Integer larguraListagemTelaEttat) {
		this.larguraListagemTelaEttat = larguraListagemTelaEttat;
	}

        /**
         *
         * @return
         */
        public Character getIndListagemTelaEttat() {
		return indListagemTelaEttat;
	}

        /**
         *
         * @param indListagemTelaEttat
         */
        public void setIndListagemTelaEttat(Character indListagemTelaEttat) {
		this.indListagemTelaEttat = indListagemTelaEttat;
	}

        /**
         *
         * @return
         */
        public Integer getSeqApresentTelaCampoEttat() {
		return seqApresentTelaCampoEttat;
	}

        /**
         *
         * @param seqApresentTelaCampoEttat
         */
        public void setSeqApresentTelaCampoEttat(Integer seqApresentTelaCampoEttat) {
		this.seqApresentTelaCampoEttat = seqApresentTelaCampoEttat;
	}

        /**
         *
         * @return
         */
        public String getLabelEstruturaEttat() {
		return labelEstruturaEttat;
	}

        /**
         *
         * @param labelEstruturaEttat
         */
        public void setLabelEstruturaEttat(String labelEstruturaEttat) {
		this.labelEstruturaEttat = labelEstruturaEttat;
	}

        /**
         *
         * @return
         */
        public Character getIndListagemImpressaResEttat() {
		return indListagemImpressaResEttat;
	}

        /**
         *
         * @param indListagemImpressaResEttat
         */
        public void setIndListagemImpressaResEttat(Character indListagemImpressaResEttat) {
		this.indListagemImpressaResEttat = indListagemImpressaResEttat;
	}

        /**
         *
         * @return
         */
        public Character getIndRelacaoImpressaEttat() {
		return indRelacaoImpressaEttat;
	}

        /**
         *
         * @param indRelacaoImpressaEttat
         */
        public void setIndRelacaoImpressaEttat(Character indRelacaoImpressaEttat) {
		this.indRelacaoImpressaEttat = indRelacaoImpressaEttat;
	}

        /**
         *
         * @return
         */
        public Character getIndRevisao() {
		return indRevisao;
	}

        /**
         *
         * @param indRevisao
         */
        public void setIndRevisao(Character indRevisao) {
		this.indRevisao = indRevisao;
	}

        /**
         *
         * @return
         */
        public String getDicaEttat() {
		return dicaEttat;
	}

        /**
         *
         * @param dicaEttat
         */
        public void setDicaEttat(String dicaEttat) {
		this.dicaEttat = dicaEttat;
	}

        /**
         *
         * @return
         */
        public Character getIndListagemItensEttat() {
		return indListagemItensEttat;
	}

        /**
         *
         * @param indListagemItensEttat
         */
        public void setIndListagemItensEttat(Character indListagemItensEttat) {
		this.indListagemItensEttat = indListagemItensEttat;
	}

        /**
         *
         * @return
         */
        public Integer getTamanhoConteudoAtribEttat() {
		return tamanhoConteudoAtribEttat;
	}

        /**
         *
         * @param tamanhoConteudoAtribEttat
         */
        public void setTamanhoConteudoAtribEttat(Integer tamanhoConteudoAtribEttat) {
		this.tamanhoConteudoAtribEttat = tamanhoConteudoAtribEttat;
	}

        /**
         *
         * @return
         */
        public Character getIndPodeBloquearEttat() {
		return indPodeBloquearEttat;
	}

        /**
         *
         * @param indPodeBloquearEttat
         */
        public void setIndPodeBloquearEttat(Character indPodeBloquearEttat) {
		this.indPodeBloquearEttat = indPodeBloquearEttat;
	}

        /**
         *
         * @return
         */
        public Character getIndFiltroEttat() {
		return indFiltroEttat;
	}

        /**
         *
         * @param indFiltroEttat
         */
        public void setIndFiltroEttat(Character indFiltroEttat) {
		this.indFiltroEttat = indFiltroEttat;
	}

        /**
         *
         * @return
         */
        public String getDocumentacaoEttat() {
		return documentacaoEttat;
	}

        /**
         *
         * @param documentacaoEttat
         */
        public void setDocumentacaoEttat(String documentacaoEttat) {
		this.documentacaoEttat = documentacaoEttat;
	}

        /**
         *
         * @return
         */
        public Character getIndExcluidoEttat() {
		return indExcluidoEttat;
	}

        /**
         *
         * @param indExcluidoEttat
         */
        public void setIndExcluidoEttat(Character indExcluidoEttat) {
		this.indExcluidoEttat = indExcluidoEttat;
	}

        /**
         *
         * @return
         */
        public Date getDataUltManutencaoEttat() {
		return dataUltManutencaoEttat;
	}

        /**
         *
         * @param dataUltManutencaoEttat
         */
        public void setDataUltManutencaoEttat(Date dataUltManutencaoEttat) {
		this.dataUltManutencaoEttat = dataUltManutencaoEttat;
	}

        /**
         *
         * @return
         */
        public Date getDataInclusaoEttat() {
		return dataInclusaoEttat;
	}

        /**
         *
         * @param dataInclusaoEttat
         */
        public void setDataInclusaoEttat(Date dataInclusaoEttat) {
		this.dataInclusaoEttat = dataInclusaoEttat;
	}


}
