package ecar.pojo;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * PontocriticoCorPtccorPK generated by hbm2java
 */
public class ItemEstrtIndResulCorIettrcorPK  implements java.io.Serializable {

	// Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -1061833835438986493L;
	private Long codIettir;
    private Long codCor;

     // Constructors

    /** default constructor */
    public ItemEstrtIndResulCorIettrcorPK() {
    }

    /** full constructor
     * @param codIettir
     * @param codCor
     */
    public ItemEstrtIndResulCorIettrcorPK(Long codIettir, Long codCor) {
       this.codIettir = codIettir;
       this.codCor = codCor;
    }
    
   
    
    @Override
    public String toString() {
        return new ToStringBuilder(this)
            .append("codIettir", getCodIettir())
            .append("codCor", getCodCor())
            .toString();
    }

    @Override
    public boolean equals(Object other) {
        if ( !(other instanceof ItemEstrtIndResulCorIettrcorPK) ) return false;
        ItemEstrtIndResulCorIettrcorPK castOther = (ItemEstrtIndResulCorIettrcorPK) other;
        return new EqualsBuilder()
            .append(this.getCodCor(), castOther.getCodCor())
            .append(this.getCodIettir(), castOther.getCodIettir())
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
            .append(getCodCor())
            .append(getCodIettir())
            .toHashCode();
    }

    /**
     *
     * @return
     */
    public Long getCodIettir() {
		return codIettir;
	}

        /**
         *
         * @param codIettir
         */
        public void setCodIettir(Long codIettir) {
		this.codIettir = codIettir;
	}

        /**
         *
         * @return
         */
        public Long getCodCor() {
		return codCor;
	}

        /**
         *
         * @param codCor
         */
        public void setCodCor(Long codCor) {
		this.codCor = codCor;
	}



}


