package ecar.pojo;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

// Generated 16/08/2006 17:15:20 by J-Querena using Hibernate Tools 3.1.0.beta5



/**
 * PontocriticoCorPtccorPK generated by hbm2java
 */
public class PontocriticoCorPtccorPK  implements java.io.Serializable {

    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -5733130042524830891L;
	private Long codPtc;
     private Long codCor;

     // Constructors

    /** default constructor */
    public PontocriticoCorPtccorPK() {
    }

    /** full constructor
     * @param codPtc
     * @param codCor
     */
    public PontocriticoCorPtccorPK(Long codPtc, Long codCor) {
       this.codPtc = codPtc;
       this.codCor = codCor;
    }
    
   
    // Property accessors
    /**
     *
     * @return
     */
    public Long getCodPtc() {
        return this.codPtc;
    }
    
    /**
     *
     * @param codPtc
     */
    public void setCodPtc(Long codPtc) {
        this.codPtc = codPtc;
    }
    /**
     *
     * @return
     */
    public Long getCodCor() {
        return this.codCor;
    }
    
    /**
     *
     * @param codCor
     */
    public void setCodCor(Long codCor) {
        this.codCor = codCor;
    }

    
    @Override
    public String toString() {
        return new ToStringBuilder(this)
            .append("codPtc", getCodPtc())
            .append("codCor", getCodCor())
            .toString();
    }

    @Override
    public boolean equals(Object other) {
        if ( !(other instanceof PontocriticoCorPtccorPK) ) return false;
        PontocriticoCorPtccorPK castOther = (PontocriticoCorPtccorPK) other;
        return new EqualsBuilder()
            .append(this.getCodCor(), castOther.getCodCor())
            .append(this.getCodPtc(), castOther.getCodPtc())
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
            .append(getCodCor())
            .append(getCodPtc())
            .toHashCode();
    }



}


