package ecar.pojo;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

// Generated 16/08/2006 17:15:20 by J-Querena using Hibernate Tools 3.1.0.beta5



/**
 * PontocriticoCorPtccor generated by hbm2java
 */
public class PontocriticoCorPtccor  implements java.io.Serializable, PaiFilho {

    // Fields    

	 private static final long serialVersionUID = 6056182336128964884L;

	 private PontocriticoCorPtccorPK id;
     private PontoCriticoPtc pontoCriticoPtc;
     private Cor cor;
     private Integer frequenciaEnvioEmailPtccor;
     private Integer antecedenciaPrimEmailPtccor;
     private String indAtivoEnvioEmailPtccor;

     // Constructors

    /** default constructor */
    public PontocriticoCorPtccor() {
    }

    /** minimal constructor
     * @param id
     * @param pontoCriticoPtc
     * @param cor
     */
    public PontocriticoCorPtccor(PontocriticoCorPtccorPK id, PontoCriticoPtc pontoCriticoPtc, Cor cor) {
        this.id = id;
        this.pontoCriticoPtc = pontoCriticoPtc;
        this.cor = cor;
    }
    /** full constructor
     * @param id
     * @param antecedenciaPrimEmailPtccor
     * @param cor
     * @param frequenciaEnvioEmailPtccor
     * @param pontoCriticoPtc
     * @param indAtivoEnvioEmailPtccor
     */
    public PontocriticoCorPtccor(PontocriticoCorPtccorPK id, PontoCriticoPtc pontoCriticoPtc, Cor cor, Integer frequenciaEnvioEmailPtccor, Integer antecedenciaPrimEmailPtccor, String indAtivoEnvioEmailPtccor) {
       this.id = id;
       this.pontoCriticoPtc = pontoCriticoPtc;
       this.cor = cor;
       this.frequenciaEnvioEmailPtccor = frequenciaEnvioEmailPtccor;
       this.antecedenciaPrimEmailPtccor = antecedenciaPrimEmailPtccor;
       this.indAtivoEnvioEmailPtccor = indAtivoEnvioEmailPtccor;
    }
    
   
    // Property accessors
    /**
     *
     * @return
     */
    public PontocriticoCorPtccorPK getId() {
        return this.id;
    }
    
    /**
     *
     * @param id
     */
    public void setId(PontocriticoCorPtccorPK id) {
        this.id = id;
    }
    /**
     *
     * @return
     */
    public PontoCriticoPtc getPontoCriticoPtc() {
        return this.pontoCriticoPtc;
    }
    
    /**
     *
     * @param pontoCriticoPtc
     */
    public void setPontoCriticoPtc(PontoCriticoPtc pontoCriticoPtc) {
        this.pontoCriticoPtc = pontoCriticoPtc;
    }
    /**
     *
     * @return
     */
    public Cor getCor() {
        return this.cor;
    }
    
    /**
     *
     * @param cor
     */
    public void setCor(Cor cor) {
        this.cor = cor;
    }
    /**
     *
     * @return
     */
    public Integer getFrequenciaEnvioEmailPtccor() {
        return this.frequenciaEnvioEmailPtccor;
    }
    
    /**
     *
     * @param frequenciaEnvioEmailPtccor
     */
    public void setFrequenciaEnvioEmailPtccor(Integer frequenciaEnvioEmailPtccor) {
        this.frequenciaEnvioEmailPtccor = frequenciaEnvioEmailPtccor;
    }
    /**
     *
     * @return
     */
    public Integer getAntecedenciaPrimEmailPtccor() {
        return this.antecedenciaPrimEmailPtccor;
    }
    
    /**
     *
     * @param antecedenciaPrimEmailPtccor
     */
    public void setAntecedenciaPrimEmailPtccor(Integer antecedenciaPrimEmailPtccor) {
        this.antecedenciaPrimEmailPtccor = antecedenciaPrimEmailPtccor;
    }
    /**
     *
     * @return
     */
    public String getIndAtivoEnvioEmailPtccor() {
        return this.indAtivoEnvioEmailPtccor;
    }
    
    /**
     *
     * @param indAtivoEnvioEmailPtccor
     */
    public void setIndAtivoEnvioEmailPtccor(String indAtivoEnvioEmailPtccor) {
        this.indAtivoEnvioEmailPtccor = indAtivoEnvioEmailPtccor;
    }

    /**
     *
     */
    public void atribuirPKPai() {
        id = new PontocriticoCorPtccorPK();        
        id.setCodCor(this.getCor().getCodCor());
        id.setCodPtc(this.getPontoCriticoPtc().getCodPtc());
		
	}
	
    @Override
	public String toString() {
        return new ToStringBuilder(this)
            .append("id", getId())
            .toString();
    }

    @Override
    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other instanceof PontocriticoCorPtccor) ) return false;
        PontocriticoCorPtccor castOther = (PontocriticoCorPtccor) other;
        return new EqualsBuilder()
            .append(this.getPontoCriticoPtc(), castOther.getPontoCriticoPtc())
            .append(this.getCor(), castOther.getCor())
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
            .append(getId())
            .toHashCode();
    }


}


