package ecar.pojo;

import java.io.Serializable;

/**
 * TipoAcompGrpAcessoId generated by MyEclipse Persistence Tools
 */

public class TipoAcompGrpAcessoId  implements Serializable {

    // Fields    

     private Long codTa;
     private Long codSatb;

    // Constructors

    /** default constructor */
    public TipoAcompGrpAcessoId() {
    }
    
    /** full constructor
     * @param codTa
     * @param codSatb
     */
    public TipoAcompGrpAcessoId(Long codTa, Long codSatb) {
        this.codTa = codTa;
        this.codSatb = codSatb;
    }
   
    // Property accessors

    /**
     *
     * @return
     */
    public Long getCodTa() {
        return this.codTa;
    }
    
    /**
     *
     * @param codTa
     */
    public void setCodTa(Long codTa) {
        this.codTa = codTa;
    }

    /**
     *
     * @return
     */
    public Long getCodSatb() {
        return this.codSatb;
    }
    
    /**
     *
     * @param codSatb
     */
    public void setCodSatb(Long codSatb) {
        this.codSatb = codSatb;
    }

    @Override
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TipoAcompGrpAcessoId) ) return false;
		 TipoAcompGrpAcessoId castOther = ( TipoAcompGrpAcessoId ) other; 
         
		 return ( (this.getCodTa()==castOther.getCodTa()) || ( this.getCodTa()!=null && castOther.getCodTa()!=null && this.getCodTa().equals(castOther.getCodTa()) ) )
 && ( (this.getCodSatb()==castOther.getCodSatb()) || ( this.getCodSatb()!=null && castOther.getCodSatb()!=null && this.getCodSatb().equals(castOther.getCodSatb()) ) );
   }
   
    @Override
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodTa() == null ? 0 : this.getCodTa().hashCode() );
         result = 37 * result + ( getCodSatb() == null ? 0 : this.getCodSatb().hashCode() );
         return result;
   }   





}