package ecar.pojo;

/**
 * TipoAcompAbasSisatributoTaAbaSatbId generated by MyEclipse Persistence Tools
 */

public class TipoAcompAbasSisatributoTaAbaSatbId implements
		java.io.Serializable {

	// Fields

	private Long codTa;
	private Long codAba;
	private Long codSatb;

	// Constructors

	/** default constructor */
	public TipoAcompAbasSisatributoTaAbaSatbId() {
	}

        /** full constructor
         * @param codTa
         * @param codAba
         * @param codSatb
         */
	public TipoAcompAbasSisatributoTaAbaSatbId(Long codTa, Long codAba,
			Long codSatb) {
		this.codTa = codTa;
		this.codAba = codAba;
		this.codSatb = codSatb;
	}

	// Property accessors

        /**
         *
         * @return
         */
        public Long getCodTa() {
		return this.codTa;
	}

        /**
         *
         * @param codTa
         */
        public void setCodTa(Long codTa) {
		this.codTa = codTa;
	}

        /**
         *
         * @return
         */
        public Long getCodAba() {
		return this.codAba;
	}

        /**
         *
         * @param codAba
         */
        public void setCodAba(Long codAba) {
		this.codAba = codAba;
	}

        /**
         *
         * @return
         */
        public Long getCodSatb() {
		return this.codSatb;
	}

        /**
         *
         * @param codSatb
         */
        public void setCodSatb(Long codSatb) {
		this.codSatb = codSatb;
	}

    @Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TipoAcompAbasSisatributoTaAbaSatbId))
			return false;
		TipoAcompAbasSisatributoTaAbaSatbId castOther = (TipoAcompAbasSisatributoTaAbaSatbId) other;

		return ((this.getCodTa() == castOther.getCodTa()) || (this.getCodTa() != null
				&& castOther.getCodTa() != null && this.getCodTa().equals(
				castOther.getCodTa())))
				&& ((this.getCodAba() == castOther.getCodAba()) || (this
						.getCodAba() != null
						&& castOther.getCodAba() != null && this.getCodAba()
						.equals(castOther.getCodAba())))
				&& ((this.getCodSatb() == castOther.getCodSatb()) || (this
						.getCodSatb() != null
						&& castOther.getCodSatb() != null && this.getCodSatb()
						.equals(castOther.getCodSatb())));
	}

    @Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodTa() == null ? 0 : this.getCodTa().hashCode());
		result = 37 * result
				+ (getCodAba() == null ? 0 : this.getCodAba().hashCode());
		result = 37 * result
				+ (getCodSatb() == null ? 0 : this.getCodSatb().hashCode());
		return result;
	}

}