package ecar.pojo;

import java.io.Serializable;



/**
 * TipoAcompGrpAcesso generated by MyEclipse Persistence Tools
 */

public class TipoAcompGrpAcesso  implements Serializable {
	
    // Fields    

     private TipoAcompGrpAcessoId id;
     private SisAtributoSatb sisAtributoSatb;
     private TipoAcompanhamentoTa tipoAcompanhamentoTa;
     private String acessoInclusao;
     private String indGerarArquivo;
     private Integer separarPorOrgao;


    // Constructors

    /** default constructor */
    public TipoAcompGrpAcesso() {
    }

    /** minimal constructor
     * @param sisAtributoSatb
     * @param tipoAcompanhamentoTa
     */
    public TipoAcompGrpAcesso(SisAtributoSatb sisAtributoSatb, TipoAcompanhamentoTa tipoAcompanhamentoTa) {
        this.id = new TipoAcompGrpAcessoId(tipoAcompanhamentoTa.getCodTa(),sisAtributoSatb.getCodSatb());
        this.sisAtributoSatb = sisAtributoSatb;
        this.tipoAcompanhamentoTa = tipoAcompanhamentoTa;
    }
    
    /** full constructor
     * @param sisAtributoSatb
     * @param separarPorOrgao
     * @param tipoAcompanhamentoTa
     * @param acessoInclusao
     */
    public TipoAcompGrpAcesso(SisAtributoSatb sisAtributoSatb, TipoAcompanhamentoTa tipoAcompanhamentoTa, String acessoInclusao, Integer separarPorOrgao) {
        this.id = new TipoAcompGrpAcessoId(tipoAcompanhamentoTa.getCodTa(),sisAtributoSatb.getCodSatb());
        this.sisAtributoSatb = sisAtributoSatb;
        this.tipoAcompanhamentoTa = tipoAcompanhamentoTa;
        this.acessoInclusao = acessoInclusao;
        this.separarPorOrgao = separarPorOrgao;
    }
   
    // Property accessors

    /**
     *
     * @return
     */
    public TipoAcompGrpAcessoId getId() {
        return this.id;
    }
    
    /**
     *
     * @param id
     */
    public void setId(TipoAcompGrpAcessoId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public SisAtributoSatb getSisAtributoSatb() {
        return this.sisAtributoSatb;
    }
    
    /**
     *
     * @param sisAtributoSatb
     */
    public void setSisAtributoSatb(SisAtributoSatb sisAtributoSatb) {
        this.sisAtributoSatb = sisAtributoSatb;
    }

    /**
     *
     * @return
     */
    public TipoAcompanhamentoTa getTipoAcompanhamentoTa() {
        return this.tipoAcompanhamentoTa;
    }
    
    /**
     *
     * @param tipoAcompanhamentoTa
     */
    public void setTipoAcompanhamentoTa(TipoAcompanhamentoTa tipoAcompanhamentoTa) {
        this.tipoAcompanhamentoTa = tipoAcompanhamentoTa;
    }

    /**
     *
     * @return
     */
    public String getAcessoInclusao() {
        return this.acessoInclusao;
    }
    
    /**
     *
     * @param acessoInclusao
     */
    public void setAcessoInclusao(String acessoInclusao) {
        this.acessoInclusao = acessoInclusao;
    }
    
   /**
    *
    * @return
    */
    public String getIndGerarArquivo() {
		return indGerarArquivo;
	}
    
   /**
    *
    * @param indGerarArquivo
    */
	public void setIndGerarArquivo(String indGerarArquivo) {
		this.indGerarArquivo = indGerarArquivo;
	}

	/**
     *
     * @return
     */
    public Integer getSepararPorOrgao() {
        return this.separarPorOrgao;
    }
    
    /**
     *
     * @param separarPorOrgao
     */
    public void setSepararPorOrgao(Integer separarPorOrgao) {
        this.separarPorOrgao = separarPorOrgao;
    }
   








}