package ecar.pojo;

/**
 * TipoAcompAbasSisatributoTaAbaSatb generated by MyEclipse Persistence Tools
 */

public class TipoAcompAbasSisatributoTaAbaSatb implements java.io.Serializable {

	// Fields

	private TipoAcompAbasSisatributoTaAbaSatbId id;
	private Aba abas;
	private SisAtributoSatb sisAtributoSatb;
	private TipoAcompanhamentoTa tipoAcompanhamentoTa;
	private String indVisualizaAba;

	// Constructors

	/** default constructor */
	public TipoAcompAbasSisatributoTaAbaSatb() {
	}

        /** minimal constructor
         * @param ta
         * @param satb
         * @param abas
         */
	public TipoAcompAbasSisatributoTaAbaSatb(
			TipoAcompanhamentoTa ta,
			Aba abas,
			SisAtributoSatb satb) {
		this.id = new TipoAcompAbasSisatributoTaAbaSatbId(ta.getCodTa(), abas.getCodAba().longValue(),satb.getCodSatb());
		this.abas = abas;
		this.sisAtributoSatb = satb;
		this.tipoAcompanhamentoTa = ta;
	}

        /** full constructor
         * @param ta
         * @param abas
         * @param satb
         * @param indVisualizaAba
         */
	public TipoAcompAbasSisatributoTaAbaSatb(
			TipoAcompanhamentoTa ta,
			Aba abas,
			SisAtributoSatb satb, 
			String indVisualizaAba) {
		this.id = new TipoAcompAbasSisatributoTaAbaSatbId(tipoAcompanhamentoTa.getCodTa(), abas.getCodAba().longValue(),sisAtributoSatb.getCodSatb());
		this.abas = abas;
		this.sisAtributoSatb = satb;
		this.tipoAcompanhamentoTa = ta;
		this.indVisualizaAba = indVisualizaAba;
	}

	// Property accessors

        /**
         *
         * @return
         */
        public TipoAcompAbasSisatributoTaAbaSatbId getId() {
		return this.id;
	}

        /**
         *
         * @param id
         */
        public void setId(TipoAcompAbasSisatributoTaAbaSatbId id) {
		this.id = id;
	}

        /**
         *
         * @return
         */
        public Aba getAbas() {
		return this.abas;
	}

        /**
         *
         * @param abas
         */
        public void setAbas(Aba abas) {
		this.abas = abas;
	}

        /**
         *
         * @return
         */
        public SisAtributoSatb getSisAtributoSatb() {
		return this.sisAtributoSatb;
	}

        /**
         *
         * @param sisAtributoSatb
         */
        public void setSisAtributoSatb(SisAtributoSatb sisAtributoSatb) {
		this.sisAtributoSatb = sisAtributoSatb;
	}

        /**
         *
         * @return
         */
        public TipoAcompanhamentoTa getTipoAcompanhamentoTa() {
		return this.tipoAcompanhamentoTa;
	}

        /**
         *
         * @param tipoAcompanhamentoTa
         */
        public void setTipoAcompanhamentoTa(
			TipoAcompanhamentoTa tipoAcompanhamentoTa) {
		this.tipoAcompanhamentoTa = tipoAcompanhamentoTa;
	}

        /**
         *
         * @return
         */
        public String getIndVisualizaAba() {
		return this.indVisualizaAba;
	}

        /**
         *
         * @param indVisualizaAba
         */
        public void setIndVisualizaAba(String indVisualizaAba) {
		this.indVisualizaAba = indVisualizaAba;
	}

}