
package ecar.webservices.pacinter;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Cadastro", targetNamespace = "http://webserviceecar.serpro.gov.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Cadastro {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "versao", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.Versao")
    @ResponseWrapper(localName = "versaoResponse", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.VersaoResponse")
    public String versao();

    /**
     * 
     * @return
     *     returns java.util.List<ecar.webservices.pacinter.DtoItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemTodos", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetItemTodos")
    @ResponseWrapper(localName = "getItemTodosResponse", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetItemTodosResponse")
    public List<DtoItem> getItemTodos();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ecar.webservices.pacinter.DtoItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemId", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetItemId")
    @ResponseWrapper(localName = "getItemIdResponse", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetItemIdResponse")
    public List<DtoItem> getItemId(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Long> arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ecar.webservices.pacinter.DtoPtc>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPtcTodos", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetPtcTodos")
    @ResponseWrapper(localName = "getPtcTodosResponse", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetPtcTodosResponse")
    public List<DtoPtc> getPtcTodos();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ecar.webservices.pacinter.DtoPtc>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPtcId", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetPtcId")
    @ResponseWrapper(localName = "getPtcIdResponse", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetPtcIdResponse")
    public List<DtoPtc> getPtcId(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Long> arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ecar.webservices.pacinter.DtoApt>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAptTodos", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetAptTodos")
    @ResponseWrapper(localName = "getAptTodosResponse", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetAptTodosResponse")
    public List<DtoApt> getAptTodos();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ecar.webservices.pacinter.DtoApt>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAptId", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetAptId")
    @ResponseWrapper(localName = "getAptIdResponse", targetNamespace = "http://webserviceecar.serpro.gov.br/", className = "ecar.webservices.pacinter.GetAptIdResponse")
    public List<DtoApt> getAptId(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Long> arg0);

}
