
package ecar.webservices.pacinter;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CadastroService", targetNamespace = "http://webserviceecar.serpro.gov.br/", wsdlLocation = "http://10.200.220.83:8080/WebServiceEcar/CadastroService?wsdl")
public class CadastroService
    extends Service
{

    private final static URL CADASTROSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ecar.webservices.pacinter.CadastroService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ecar.webservices.pacinter.CadastroService.class.getResource(".");
            url = new URL(baseUrl, "http://10.200.220.83:8080/WebServiceEcar/CadastroService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.200.220.83:8080/WebServiceEcar/CadastroService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CADASTROSERVICE_WSDL_LOCATION = url;
    }

    public CadastroService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadastroService() {
        super(CADASTROSERVICE_WSDL_LOCATION, new QName("http://webserviceecar.serpro.gov.br/", "CadastroService"));
    }

    /**
     * 
     * @return
     *     returns Cadastro
     */
    @WebEndpoint(name = "CadastroPort")
    public Cadastro getCadastroPort() {
        return super.getPort(new QName("http://webserviceecar.serpro.gov.br/", "CadastroPort"), Cadastro.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cadastro
     */
    @WebEndpoint(name = "CadastroPort")
    public Cadastro getCadastroPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webserviceecar.serpro.gov.br/", "CadastroPort"), Cadastro.class, features);
    }

}
