package ecar.pojo.historico;

//Generated 01/12/2008 10:09:26 by Hibernate Tools 3.2.2.GA

import java.io.Serializable;
import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

import ecar.pojo.UsuarioUsu;

/**
* Historicoxml generated by hbm2java
*/
public class HistoricoXml implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1020962725046293298L;
	
	private Long codigo;
	private byte[] objeto;
	
	private String historico;
	private UsuarioUsu usuarioUsu;
	private Date dataHistorico;
	private Long tipoHistorico;
	private Long idObjetoSerializado;
	

        /**
         *
         */
        public HistoricoXml() {
	}

        /**
         *
         * @param codigo
         */
        public HistoricoXml(long codigo) {
		this.codigo = codigo;
	}

        /**
         *
         * @return
         */
        public Long getCodigo() {
		return this.codigo;
	}

        /**
         *
         * @param codigo
         */
        public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

        /**
         *
         * @return
         */
        public UsuarioUsu getUsuarioUsu() {
		return this.usuarioUsu;
	}

        /**
         *
         * @param usuarioUsu
         */
        public void setUsuarioUsu(UsuarioUsu usuarioUsu) {
		this.usuarioUsu = usuarioUsu;
	}

        /**
         *
         * @return
         */
        public byte[] getObjeto() {
		return this.objeto;
	}

        /**
         *
         * @param objeto
         */
        public void setObjeto(byte[] objeto) {
		this.objeto = objeto;
	}

        /**
         *
         * @return
         */
        public Date getDataHistorico() {
		return this.dataHistorico;
	}

        /**
         *
         * @param dataHistorico
         */
        public void setDataHistorico(Date dataHistorico) {
		this.dataHistorico = dataHistorico;
	}

        /**
         *
         * @return
         */
        public Long getTipoHistorico() {
		return this.tipoHistorico;
	}

        /**
         *
         * @param tipoHistorico
         */
        public void setTipoHistorico(Long tipoHistorico) {
		this.tipoHistorico = tipoHistorico;
	}

        /**
         *
         * @return
         */
        public String getHistorico() {
		return this.historico;
	}

        /**
         *
         * @param historico
         */
        public void setHistorico(String historico) {
		this.historico = historico;
	}


    @Override
    public String toString() {
        return new ToStringBuilder(this)
            .append("codigo", getCodigo())
            .toString();
    }

    @Override
    public boolean equals(Object other) {
        if ( !(other instanceof HistoricoXml) ) return false;
        HistoricoXml castOther = (HistoricoXml) other;
        return new EqualsBuilder()
            .append(this.getCodigo(), castOther.getCodigo())
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
            .append(getCodigo())
            .toHashCode();
    }

    /**
     *
     * @return
     */
    public Long getIdObjetoSerializado() {
		return idObjetoSerializado;
	}

    /**
     *
     * @param idObjetoSerializado
     */
    public void setIdObjetoSerializado(Long idObjetoSerializado) {
		this.idObjetoSerializado = idObjetoSerializado;
	}



}
